import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans, Oxanium } from "next/font/google";
import "./globals.css";
import "@xterm/xterm/css/xterm.css";
import {
  SidebarProvider,
} from "@/components/ui/sidebar";

import { cn } from "@/lib/utils";
import {AppSideBar} from "@/src/app/_components";

const geistHeading = Geist({subsets:['latin'],variable:'--font-heading'});

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="kr"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", geist.variable, geistHeading.variable)}
    >
      <body className="min-h-full flex flex-col">
        <SidebarProvider>
          <AppSideBar />
          <main className={'w-full h-full'}>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
